import { z } from 'zod';
import { tool, nodePath, anyValue, EDITOR_PATH_NOTE, VALUE_NOTE } from './types.js';

const g = 'node';

export const nodeTools = [
  tool({ group: g, name: 'add_node',
    description: `Add a node to the edited scene. type is a ClassDB name (Sprite2D, Label, CharacterBody2D…) or a script class_name. ${EDITOR_PATH_NOTE} ${VALUE_NOTE}`,
    input: { type: z.string(), parent_path: nodePath('Parent, default "." (root).').optional(), name: z.string().optional(), properties: z.record(z.string(), z.any()).describe('Initial property values.').optional() } }),
  tool({ group: g, name: 'delete_node', destructive: true,
    description: `Delete a node (undoable). ${EDITOR_PATH_NOTE}`,
    input: { node_path: nodePath() } }),
  tool({ group: g, name: 'duplicate_node',
    description: 'Duplicate a node next to itself.',
    input: { node_path: nodePath(), name: z.string().optional() } }),
  tool({ group: g, name: 'move_node',
    description: 'Reparent a node.',
    input: { node_path: nodePath(), new_parent_path: nodePath('New parent path.') } }),
  tool({ group: g, name: 'update_property',
    description: `Set a property on a node in the edited scene (undoable). ${EDITOR_PATH_NOTE} ${VALUE_NOTE}`,
    input: { node_path: nodePath(), property: z.string(), value: anyValue() } }),
  tool({ group: g, name: 'get_node_properties', readOnly: true,
    description: 'Read all properties of a node (optionally only those whose name starts with category).',
    input: { node_path: nodePath(), category: z.string().optional() } }),
  tool({ group: g, name: 'add_resource',
    description: 'Create a new resource (e.g. RectangleShape2D, StandardMaterial3D, StyleBoxFlat) and assign it to a node property.',
    input: { node_path: nodePath(), property: z.string().describe('Property to assign, e.g. "shape", "texture", "material".'), resource_type: z.string(), resource_properties: z.record(z.string(), z.any()).optional() } }),
  tool({ group: g, name: 'set_anchor_preset',
    description: 'Apply a Control anchor preset.',
    input: { node_path: nodePath(), preset: z.enum(['top_left','top_right','bottom_left','bottom_right','center_left','center_top','center_right','center_bottom','center','left_wide','top_wide','right_wide','bottom_wide','vcenter_wide','hcenter_wide','full_rect']), keep_offsets: z.boolean().optional() } }),
  tool({ group: g, name: 'rename_node',
    description: 'Rename a node.',
    input: { node_path: nodePath(), new_name: z.string() } }),
  tool({ group: g, name: 'connect_signal',
    description: 'Connect a signal from one node to a method on another (persisted in the scene).',
    input: { source_path: nodePath('Emitter node path.'), signal_name: z.string(), target_path: nodePath('Receiver node path.'), method_name: z.string(), deferred: z.boolean().optional(), one_shot: z.boolean().optional() } }),
  tool({ group: g, name: 'disconnect_signal',
    description: 'Disconnect a previously connected signal.',
    input: { source_path: nodePath('Emitter node path.'), signal_name: z.string(), target_path: nodePath('Receiver node path.'), method_name: z.string() } }),
  tool({ group: g, name: 'get_node_groups', readOnly: true,
    description: 'List the groups a node belongs to.',
    input: { node_path: nodePath() } }),
  tool({ group: g, name: 'set_node_groups',
    description: 'Set the complete group list for a node (groups not listed are removed).',
    input: { node_path: nodePath(), groups: z.array(z.string()) } }),
  tool({ group: g, name: 'find_nodes_in_group', readOnly: true,
    description: 'Find nodes in the edited scene that belong to a group.',
    input: { group: z.string() } }),
  tool({ group: g, name: 'get_editor_selection', readOnly: true,
    description: 'Nodes currently selected in the editor.',
    input: { top_only: z.boolean().optional() } }),
  tool({ group: g, name: 'select_nodes',
    description: 'Select nodes in the editor (and optionally show them in the Inspector).',
    input: { node_paths: z.array(z.string()).optional(), node_path: nodePath().optional(), mode: z.enum(['replace','add','remove']).optional(), inspect: z.boolean().optional(), focus: z.boolean().optional(), inspector_only: z.boolean().optional(), for_property: z.string().optional() } }),
  tool({ group: g, name: 'clear_editor_selection',
    description: 'Clear the editor selection.',
    input: {} }),
];
