import { z } from 'zod';
import { tool, gamePath, anyValue, RUNTIME_PATH_NOTE } from './types.js';

const g = 'runtime';
const strList = z.array(z.string());

export const runtimeTools = [
  tool({ group: g, name: 'get_game_scene_tree', readOnly: true,
    description: `Live node tree of the running game with absolute paths. ${RUNTIME_PATH_NOTE}`,
    input: { max_depth: z.number().int().optional(), script_filter: z.string().describe('Only nodes whose script path contains this.').optional(), type_filter: z.string().optional(), named_only: z.boolean().optional() } }),
  tool({ group: g, name: 'get_game_node_properties', readOnly: true,
    description: `Read runtime property values of a node in the running game. ${RUNTIME_PATH_NOTE}`,
    input: { node_path: gamePath(), properties: strList.describe('Specific properties; omit for all.').optional() } }),
  tool({ group: g, name: 'set_game_node_property',
    description: `Set a property on a node in the running game. String values are evaluated as Godot expressions ("Vector2(1,2)", "Color.RED"). ${RUNTIME_PATH_NOTE}`,
    input: { node_path: gamePath(), property: z.string(), value: anyValue() } }),
  tool({ group: g, name: 'capture_frames', readOnly: true, timeoutMs: (a) => Math.min(((a.count ?? 5) * (a.frame_interval ?? 10)) / 60 + 2, 25) * 1000 + 15_000,
    images: (r) => (Array.isArray(r?.frames) ? r.frames.map((f: string) => ({ type: 'image' as const, data: f, mimeType: 'image/png' })) : []),
    description: 'Capture several frames of the running game over time (returned as images, up to 10 shown). count 1-30, frame_interval frames between captures, half_resolution default true.',
    input: { count: z.number().int().optional(), frame_interval: z.number().int().optional(), half_resolution: z.boolean().optional() } }),
  tool({ group: g, name: 'monitor_properties', readOnly: true, timeoutMs: (a) => Math.min(((a.frame_count ?? 60) * (a.frame_interval ?? 1)) / 60 + 2, 25) * 1000 + 15_000,
    description: `Sample node properties every frame_interval frames for frame_count frames (e.g. track position/velocity over time). ${RUNTIME_PATH_NOTE}`,
    input: { node_path: gamePath(), properties: strList, frame_count: z.number().int().optional(), frame_interval: z.number().int().optional() } }),
  tool({ group: g, name: 'execute_game_script', timeoutMs: 25_000,
    description: 'Run GDScript inside the running game (code is the body of a function with access to the scene tree via get_tree()). Returns printed output / return value.',
    input: { code: z.string() } }),
  tool({ group: g, name: 'start_recording',
    description: 'Start recording player input events in the running game.',
    input: {} }),
  tool({ group: g, name: 'stop_recording',
    description: 'Stop recording and return the captured input events (pass them to replay_recording).',
    input: {} }),
  tool({ group: g, name: 'replay_recording', timeoutMs: (a) => {
      const events = Array.isArray(a.events) ? a.events : [];
      const maxMs = events.reduce((m: number, e: any) => Math.max(m, Number(e?.time_ms) || 0), 0);
      return Math.min(maxMs / (a.speed ?? 1) + 5000, 120_000) + 15_000;
    },
    description: 'Replay input events captured by stop_recording at the given speed multiplier.',
    input: { events: z.array(z.record(z.string(), z.any())), speed: z.number().optional() } }),
  tool({ group: g, name: 'find_nodes_by_script', readOnly: true,
    description: 'Find runtime nodes whose script path contains the given string; optionally read properties from each.',
    input: { script: z.string(), properties: strList.optional() } }),
  tool({ group: g, name: 'get_autoload', readOnly: true,
    description: 'Read properties of an autoload singleton in the running game (bare name, e.g. "GameState").',
    input: { name: z.string(), properties: strList.optional() } }),
  tool({ group: g, name: 'batch_get_properties', readOnly: true,
    description: `Read properties from several runtime nodes at once. nodes: [{node_path, properties?}]. ${RUNTIME_PATH_NOTE}`,
    input: { nodes: z.array(z.object({ node_path: z.string(), properties: strList.optional() })) } }),
  tool({ group: g, name: 'find_ui_elements', readOnly: true,
    description: 'List visible Control nodes (buttons, labels…) in the running game with their text and paths.',
    input: { type_filter: z.string().optional() } }),
  tool({ group: g, name: 'click_button_by_text',
    description: 'Press a button in the running game by its visible text.',
    input: { text: z.string(), partial: z.boolean().optional() } }),
  tool({ group: g, name: 'wait_for_node', readOnly: true, timeoutMs: (a) => ((a.timeout ?? 5) + 2) * 1000 + 10_000,
    description: `Wait until a node exists in the running game (or timeout seconds pass). ${RUNTIME_PATH_NOTE}`,
    input: { node_path: gamePath(), timeout: z.number().optional(), poll_frames: z.number().int().optional() } }),
  tool({ group: g, name: 'find_nearby_nodes', readOnly: true,
    description: 'Find runtime nodes within radius of a position ({x,y} or {x,y,z}), optionally filtered by type or group.',
    input: { position: z.any(), radius: z.number().optional(), type_filter: z.string().optional(), group_filter: z.string().optional(), max_results: z.number().int().optional() } }),
  tool({ group: g, name: 'navigate_to',
    description: 'Teleport/aim the player toward a target (position or node path) in the running game. player_path defaults to /root/Main/Player.',
    input: { target: z.any(), player_path: z.string().optional(), camera_path: z.string().optional(), move_speed: z.number().optional() } }),
  tool({ group: g, name: 'move_to', timeoutMs: (a) => ((a.timeout ?? 15) + 5) * 1000 + 10_000,
    description: 'Drive the player toward a target using simulated input until within arrival_radius or timeout seconds. player_path defaults to /root/Main/Player.',
    input: { target: z.any(), player_path: z.string().optional(), camera_path: z.string().optional(), arrival_radius: z.number().optional(), timeout: z.number().optional(), run: z.boolean().optional(), look_at_target: z.boolean().optional() } }),
  tool({ group: g, name: 'watch_signals', readOnly: true, timeoutMs: (a) => (a.duration_ms ?? 5000) + 5000 + 10_000,
    description: `Record signals emitted by the given runtime nodes for duration_ms. ${RUNTIME_PATH_NOTE}`,
    input: { node_paths: strList, signal_filter: strList.optional(), duration_ms: z.number().int().optional() } }),
];
