import { z } from 'zod';
import { tool, nodePath, resPath, vec, color } from './types.js';

const g = 'scene_3d';
const V = 'as {x,y,z} or "Vector3(x, y, z)".';

export const scene3dTools = [
  tool({ group: g, name: 'add_mesh_instance',
    description: 'Add a MeshInstance3D with a primitive (mesh_type: BoxMesh, SphereMesh, CylinderMesh, CapsuleMesh, PlaneMesh, PrismMesh, TorusMesh, QuadMesh) or an imported model (mesh_file .glb/.gltf/.obj).',
    input: { mesh_type: z.string().optional(), mesh_file: resPath('Model file path.').optional(), parent_path: nodePath('Parent, default ".".').optional(), name: z.string().optional(), mesh_properties: z.record(z.string(), z.any()).describe('e.g. {"size": "Vector3(2,1,2)", "radius": 0.5}').optional(), position: vec('Position ' + V).optional(), rotation: vec('Rotation degrees ' + V).optional(), scale: vec('Scale ' + V).optional() } }),
  tool({ group: g, name: 'setup_lighting',
    description: 'Add a light. Either light_type (DirectionalLight3D, OmniLight3D, SpotLight3D) or preset (sun, indoor, dramatic).',
    input: { light_type: z.string().optional(), preset: z.enum(['sun','indoor','dramatic']).optional(), parent_path: nodePath('Parent, default ".".').optional(), name: z.string().optional(), color: color().optional(), energy: z.number().optional(), shadows: z.boolean().optional(), range: z.number().optional(), attenuation: z.number().optional(), spot_angle: z.number().optional(), spot_angle_attenuation: z.number().optional(), position: vec('Position ' + V).optional(), rotation: vec('Rotation degrees ' + V).optional() } }),
  tool({ group: g, name: 'set_material_3d',
    description: 'Create/edit a StandardMaterial3D on a MeshInstance3D surface: PBR albedo, metallic, roughness, emission, textures, transparency, cull_mode.',
    input: { node_path: nodePath(), surface_index: z.number().int().optional(), albedo_color: color().optional(), albedo_texture: z.string().optional(), metallic: z.number().optional(), roughness: z.number().optional(), metallic_texture: z.string().optional(), roughness_texture: z.string().optional(), normal_texture: z.string().optional(), emission: color().optional(), emission_color: color().optional(), emission_energy: z.number().optional(), emission_texture: z.string().optional(), transparency: z.string().describe('disabled | alpha | alpha_scissor | alpha_hash | alpha_depth_pre_pass').optional(), cull_mode: z.string().describe('back | front | disabled').optional() } }),
  tool({ group: g, name: 'setup_environment',
    description: 'Create or edit a WorldEnvironment: background (sky/color), ambient light, tonemap, fog, glow, SSAO, SSR, SDFGI. Pass node_path to edit an existing one.',
    input: { parent_path: nodePath('Parent for a new node.').optional(), name: z.string().optional(), node_path: nodePath('Existing WorldEnvironment to edit.').optional(), background_mode: z.string().describe('sky | color | clear_color | canvas').optional(), background_color: color().optional(), sky: z.object({ sky_top_color: z.any().optional(), sky_horizon_color: z.any().optional(), ground_bottom_color: z.any().optional(), ground_horizon_color: z.any().optional(), sun_angle_max: z.number().optional(), sky_curve: z.number().optional() }).optional(), ambient_light_color: color().optional(), ambient_light_energy: z.number().optional(), ambient_light_source: z.string().optional(), tonemap_mode: z.string().describe('linear | reinhard | filmic | aces').optional(), tonemap_exposure: z.number().optional(), tonemap_white: z.number().optional(), fog_enabled: z.boolean().optional(), fog_light_color: color().optional(), fog_density: z.number().optional(), fog_light_energy: z.number().optional(), glow_enabled: z.boolean().optional(), glow_intensity: z.number().optional(), glow_strength: z.number().optional(), glow_bloom: z.number().optional(), ssao_enabled: z.boolean().optional(), ssao_radius: z.number().optional(), ssao_intensity: z.number().optional(), ssr_enabled: z.boolean().optional(), ssr_max_steps: z.number().int().optional(), ssr_fade_in: z.number().optional(), ssr_fade_out: z.number().optional(), sdfgi_enabled: z.boolean().optional() } }),
  tool({ group: g, name: 'setup_camera_3d',
    description: 'Create or edit a Camera3D (projection perspective|orthogonal, fov, near/far, position, rotation or look_at, make current).',
    input: { parent_path: nodePath('Parent for a new node.').optional(), node_path: nodePath('Existing Camera3D to edit.').optional(), name: z.string().optional(), projection: z.string().optional(), fov: z.number().optional(), size: z.number().optional(), near: z.number().optional(), far: z.number().optional(), cull_mask: z.number().int().optional(), current: z.boolean().optional(), position: vec('Position ' + V).optional(), rotation: vec('Rotation degrees ' + V).optional(), look_at: vec('Point to look at ' + V).optional(), environment_path: z.string().optional() } }),
  tool({ group: g, name: 'add_gridmap',
    description: 'Create or edit a GridMap with a MeshLibrary and optionally place cells [{x,y,z,item,orientation?}].',
    input: { parent_path: nodePath('Parent for a new node.').optional(), name: z.string().optional(), node_path: nodePath('Existing GridMap to edit.').optional(), mesh_library_path: z.string().optional(), cell_size: vec('Cell size ' + V).optional(), position: vec('Position ' + V).optional(), cells: z.array(z.object({ x: z.number().int(), y: z.number().int(), z: z.number().int(), item: z.number().int(), orientation: z.number().int().optional() })).optional() } }),
];
